# Generated by Django 5.2.7 on 2025-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('population', models.FloatField()),
                ('climates', models.CharField(blank=True, default=None, max_length=100)),
                ('terrains', models.CharField(blank=True, default=None, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
