# Generated by Django 5.2.7 on 2025-10-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
