# Generated by Django 5.2.7 on 2025-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuel', '0002_alter_planet_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climates',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrains',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
